# Generated by Django 5.2.4 on 2025-10-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='rname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
