# Generated by Django 5.2.4 on 2025-08-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveBigIntegerField(),
        ),
    ]
